apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rutsw8zxq-go 
  janus-idp.io/tekton: rutsw8zxq-go
  backstage.io/kubernetes-id: rutsw8zxq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rutsw8zxq-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml