apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rutsw8zxq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rutsw8zxq-go 
  name: rutsw8zxq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rutsw8zxq-go 
